# 06 - Material Comparison
Coolants and semiconductors side by side.

In [1]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
plt.rcParams.update({'figure.dpi': 110, 'font.size': 11})
from simulations.coolant import coolant_ranking_table
from simulations.semiconductors import material_comparison_table
coolant_ranking_table(100e6, 20.0)

,Coolant,Cp [J/kg/K],Density [kg/m3],k [W/m/K],Liquid range [K],Max liquid T [K],Vapour p @op [Pa],Mass flow [kg/s],Pumping power [W],Pumping fraction
0,Ammonia,4700.0,610.0,0.500,44.4,239.80,1000000.000,1063.829787,1.095340e+06,0.010953
1,Lithium,4170.0,512.0,45.000,1161.3,1615.00,0.010,1199.040767,1.708963e+06,0.017090
2,Water,4186.0,997.0,0.606,100.0,373.15,3200.000,1194.457716,1.758368e+06,0.017584
3,Molten salt (solar salt 60NaNO3-40KNO3),1500.0,1899.0,0.520,379.0,873.00,0.010,3333.333333,5.663174e+06,0.056632
4,NaK (eutectic 22Na-78K),982.0,866.0,22.000,797.5,1058.00,0.001,5091.649695,6.728246e+06,0.067282

In [2]:
material_comparison_table(100e6)

,Material,Bandgap [eV],k [W/m/K],Max Tj [K],Max Tj [C],Radiator T [K],Radiator area [m2],Radiator mass [kg],Rad tolerance,TRL,Mass vs silicon
0,Silicon (Si),1.12,150.0,398.0,124.85,343.0,74948.485874,524639.401115,moderate,9,1.000000
1,Gallium Nitride (GaN),3.40,160.0,573.0,299.85,518.0,14408.550844,100859.855905,high,7,0.192246
2,Silicon Carbide (4H-SiC),3.26,370.0,623.0,349.85,568.0,9966.576380,69766.034662,high,8,0.132979
3,Gallium Oxide (beta-Ga2O3),4.80,23.0,773.0,499.85,718.0,3903.386584,27323.706088,high,4,0.052081
4,Diamond semiconductor,5.47,2200.0,1073.0,799.85,1018.0,965.935728,6761.550096,very high,3,0.012888